version: 7.4.{build}

branches:
  only:
    - master
    - appveyor

skip_tags: true

image:
  - Visual Studio 2022

jobs:
  build:
    name: Build UWP MSIX Package
    steps:
      - script: |
          echo Initializing Submodules...
          git submodule init
          git submodule update
      - script: |
          echo Installing Dependencies...
          call "%APPVEYOR_BUILD_FOLDER%\.appveyor\Install.bat"
      - script: |
          echo Building UWP MSIX Package...
          msbuild "%APPVEYOR_BUILD_FOLDER%\src_rebuild\MyApp.sln" ^
            /p:AppxBundlePlatforms=x64 ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /t:Restore,Rebuild
      - script: |
          echo Running Post-Build Steps...
          call "%APPVEYOR_BUILD_FOLDER%\.appveyor\AfterBuild.bat"

artifacts:
  # Collect the UWP MSIX package
  - path: '%APPVEYOR_BUILD_FOLDER%\msix\*.msix'
    name: MSIX Package

cache:
  - '%APPVEYOR_BUILD_FOLDER%\dependencies'
  - '%APPVEYOR_BUILD_FOLDER%\msix'
  
