name: Build UWP MSIX Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build MSIX Package
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Initialize submodules
      - name: Initialize Submodules
        run: |
          git submodule init
          git submodule update

      # Step 3: Set up dependencies
      - name: Install Dependencies
        run: |
          .\appveyor\Install.bat

      # Step 4: Build UWP MSIX Package
      - name: Build MSIX Package
        run: |
          msbuild .\src_rebuild\MyApp.sln `
            /p:AppxBundlePlatforms=x64 `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /t:Restore,Rebuild

      # Step 5: Post-build steps (if needed)
      - name: Post-Build Steps
        run: |
          .\appveyor\AfterBuild.bat

      # Step 6: Upload the MSIX as an artifact
      - name: Upload MSIX Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MSIX Package
          path: msix/*.msix
          
